app/frontend/config/routes.rb
Rails.application.routes.draw do
  root to: 'roots#redirect_to_getstarted'
  get '/cleaner', to: 'roots#redirect_to_getstarted'

  direct :blog do
    'http://blog.kurorekishi.me'
  end
  scope 'cleaner' do
    get '/getstarted', to: 'roots#show',    as: :getstarted
    get '/usage',      to: 'roots#usage',   as: 'usage'
    get '/faq',        to: 'roots#faq',     as: 'faq'
    get '/terms',      to: 'roots#terms',   as: 'terms'
    get '/privacy',    to: 'roots#privacy', as: 'privacy'
    get '/contact',    to: 'roots#contact', as: 'contact'

    get '/auth/twitter', as: :signin
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/signout', as: :signout, to: 'sessions#destroy'

    resource :order, only: [:show, :new, :create] do
      get :progressbar, on: :member
      get :status_dialog, on: :member
      get :result, on: :member
      post :abort, on: :member
      post :confirm, on: :member
      post :close, on: :member
    end
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/frontend/app/models/ad_unit.rb
class AdUnit < ActiveHash::Base
  fields :id, :unit

  create id:  0, unit: 1717409875
  create id:  1, unit: 1298607478
  create id:  2, unit: 8682273472
  create id:  3, unit: 2635849070
  create id:  4, unit: 2551100271
  create id:  5, unit: 2481073070
  create id:  6, unit: 7065308278
  create id:  7, unit: 2655349078
  create id:  8, unit: 8113994274
  create id:  9, unit: 7066048677
  create id: 10, unit: 1213967877
  create id: 11, unit: 7205727471
  create id: 12, unit: 9737093877
  create id: 13, unit: 9178690672
  create id: 14, unit: 9989918276
  create id: 15, unit: 1220670557
  create id: 16, unit: 6426811070
  create id: 17, unit: 7903544277
  create id: 18, unit: 9380277476
  create id: 19, unit: 1857010671
  create id: 20, unit: 4810477079
  create id: 21, unit: 3194143077
  create id: 22, unit: 7763943475
  create id: 23, unit: 9240676671

  create id: 97, unit: 8736983874
  create id: 98, unit: 4171805877
  create id: 99, unit: 3256867075

  def self.current
    find(Time.zone.now.hour).unit
  end
end

app/frontend/app/models/server_status.rb
class ServerStatus
  include ActiveModel::Model
  extend ActiveModel::Naming

  BUSYNESS_EMPTY  = :empty
  BUSYNESS_NORMAL = :normal
  BUSYNESS_JAM    = :jam
  BUSYNESS_HALT   = :halt

  attr_accessor :busyness, :processing_count

  class << self
    def current_server_status
      new.tap do |status|
        status.busyness         = busyness
        status.processing_count = processing_count
      end
    end

    private

    def processing_count
      Order.processing.count
    end

    def busyness
      processing_count.try do |count|
        (count <= 25)  ? BUSYNESS_EMPTY  :
        (count <= 50)  ? BUSYNESS_NORMAL :
        (count <= 100) ? BUSYNESS_JAM
                       : BUSYNESS_HALT
      end
    end
  end
end

app/frontend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  include Authable

  def redirect_to_getstarted
    redirect_to getstarted_path
  end
end

app/frontend/app/controllers/concerns/authable.rb
module Authable
  extend ActiveSupport::Concern

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    reset_session
  end

  def logged_in?
    current_user.present?
  end
end

app/frontend/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :welcome_crawler, only: :show
  before_action :require_logged_in
  before_action :require_active_order_is_non_existent, only: :new
  before_action :require_active_order_is_existent, only: [:show, :progressbar, :status_dialog]
  before_action :require_closing_order_is_existent, only: :result

  def new
    @form = OrderForm.new(order_params)
  end

  def show
    @order = find_order.decorate
    @server_status = ServerStatusDecorator.decorate(
      ServerStatus.current_server_status
    )
  end

  def result
    @order = find_order.decorate
  end

  def create
    @form = OrderForm.new(order_params)

    if @form.valid?
      @form.save!

      redirect_to order_path
    else
      render :new
    end
  end

  def abort
    order = find_order
    order.abort! if order.may_abort?
    redirect_to order_path
  end

  def confirm
    order = find_order
    order.confirm! if order.may_confirm?
    redirect_to result_order_path
  end

  def close
    order = find_order
    order.close! if order.may_close?
    redirect_to getstarted_path
  end

  def progressbar
    @order = find_order.decorate
    render 'progressbar', layout: false
  end

  def status_dialog
    @order = find_order.decorate
    @server_status = ServerStatusDecorator.decorate(
      ServerStatus.current_server_status
    )
    render 'status_dialog', layout: false
  end

  private

  def find_order
    Order.user(current_user).active.first
  end

  def order_params
    params.permit(
      :collect_method, :archive_url,
      :start_message, :finish_message,
      :protect_reply, :protect_favorite, :collect_from, :collect_to,
    ).merge(user_id: current_user.id)
  end

  def welcome_crawler
    return if current_user.present?
    render 'roots/show'
  end

  def require_logged_in
    return if logged_in?
    redirect_to root_path
  end

  def require_active_order_is_non_existent
    return if find_order.blank?
    redirect_to order_path
  end

  def require_active_order_is_existent
    return if find_order.present?
    redirect_to new_order_path
  end

  def require_closing_order_is_existent
    return if find_order.closing?
    redirect_to order_path
  end
end

app/frontend/app/controllers/roots_controller.rb
class RootsController < ApplicationController
  def getstarted; end
end

app/frontend/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  rescue_from Exception, with: :invalid_session_exception

  def create
    signin = SigninForm.new(auth_hash)

    if signin.valid?
      signin.save!

      session[:user_id] = signin.user_id
      redirect_to new_order_path
    else
      reset_session
      redirect_to root_path, alert: '認証が正しく行われませんでした'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, alert: 'ログアウトしました'
  end

  def failure
    reset_session
    redirect_to root_path, alert: '認証が正しく行われませんでした'
  end

  protected

  def invalid_session_exception(ex)
    reset_session
    raise ex
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/frontend/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    if alert.present?
      tag.div class: 'wrapped-content' do
        tag.div class: 'panel radius lightpurple text-center' do
          alert
        end
      end
    elsif notice.present?
      tag.div class: 'wrapped-content' do
        tag.div class: 'panel radius success text-center' do
          notice
        end
      end
    end
  end
end

app/frontend/app/views/application/_analytics.html.erb
<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-5926301-11', {'cookiePath': '/cleaner'});
    ga('send', 'pageview');
  </script>
<% end %>

app/frontend/app/views/application/adsense/_rectangle.html.erb
<div class='ad'>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:336px;height:280px"
     data-ad-client="ca-pub-4435381701402377"
     data-ad-slot="<%= AdUnit.current -%>"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

app/frontend/app/views/layouts/_header.html.haml
%header#header
  #menu-trigger.header-button.left.icon-menu
  %h1= link_to '黒歴史クリーナー', root_path, class: 'main-title'

app/frontend/app/views/layouts/_meta.html.haml
-# display settings
%meta(charset='utf-8')
%meta(http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1')
%meta(name='viewport' content='width=device-width, user-scalable=no')
-# basic information
%meta(name='keywords' content='Twitter Tweet ツイッター ツイート 削除 炎上予防')
%meta(name='description' content='「黒歴史クリーナー」はツイート一括削除サービス！簡単・迅速にあなたの黒歴史を消去します。炎上予防のため定期的にツイートを削除したい方、フォロワーを消さずにTwitterをやり直したい方にオススメです！')
%link(rel='canonical' href='https://kurorekishi.me/cleaner')
-# open graph
%meta(property="og:title" content="呪われしツイートを一括削除！ | 黒歴史クリーナー")
%meta(property="og:site_name" content="黒歴史クリーナー")
%meta(property="og:description" content="「黒歴史クリーナー」はツイート一括削除サービス！簡単・迅速にあなたの黒歴史を消去します。炎上予防のため定期的にツイートを削除したい方、フォロワーを消さずにTwitterをやり直したい方にオススメです！")
%meta(property="og:type" content="website")
%meta(property="og:url" content="https://kurorekishi.me/cleaner")
%meta{property:"og:image", content:image_url('app-image.png')}
-# twitter cards
%meta(name="twitter:card" content="summary")
%meta(name="twitter:site" content="@CleanThemAll")
%meta(name="twitter:domain" content="kurorekishi.me")
-# facebook app
%meta(property="fb:admins" content="100000506059314")
%meta(property="fb:app_id" content="470879106306179")
-# smartphone
%meta(apple-mobile-web-app-status-bar-style='black-translucent')
%link{rel:"apple-touch-icon-precomposed", sizes:"120x120", href:image_url('apple-touch-icon-precomposed.png')}
%link{rel:"apple-touch-icon-precomposed", sizes:"144x144", href:image_url('apple-touch-icon-precomposed.png')}
%link{rel:"apple-touch-icon", sizes:"120x120", href:image_url('apple-touch-icon-precomposed.png')}
%link{rel:"apple-touch-icon", sizes:"144x144", href:image_url('apple-touch-icon-precomposed.png')}
%meta(name='apple-mobile-web-app-title' content='CleanThemAll')

app/frontend/app/views/layouts/_sidebar.html.haml
%aside#sidemenu-container
  #sidemenu
    #author-profile
      .author-profile-photo
        = image_tag('profile.png')
      .author-profile-content
        %p.title
          黒歴史クリーナー
        %p.subtitle
          @CleanThemAll
    %nav#nav-container
      %ul.nav
        %li
          = link_to 'Home', root_path
        %li
        - if logged_in?
          = link_to 'ログアウト', signout_path
        - else
          = link_to 'ログイン', signin_path
        %li
          = render partial: 'layouts/sidebar/welcome.html.haml'
        %li
          = render partial: 'layouts/sidebar/services.html.haml'

app/frontend/app/views/layouts/application.html.haml
!!! 5
%html(lang='en')
  %head(prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#")
    = render 'layouts/meta'
    %title 黒歴史クリーナー
    = favicon_link_tag('favicon.ico')
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    = javascript_include_tag 'application'
    = render 'application/analytics'
    = yield :page_scripts
  %body
    #container
      = render partial: 'layouts/sidebar'
      %section#content-container.dark.clearfix
        = render partial: 'layouts/header'
        = yield
    = yield :scripts

app/frontend/app/views/layouts/maintenance.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
    <meta content='width=device-width, user-scalable=no, initial-scale=1.0' name='viewport'>
    <meta apple-mobile-web-app-status-bar-style='black-translucent'>
    <meta content='CleanThemAll' name='apple-mobile-web-app-title'>
    <title>呪われしツイートを一括削除！ | 黒歴史クリーナー</title>
    <style type="text/css">
    body {
      width: 400px;
      margin: 100px auto;
      font: 300 120% "OpenSans", "Helvetica Neue", "Helvetica", Arial, Verdana, sans-serif;
      color: #444;
    }
    h1 { font-weight: 300; }
    .date{ color: #da4f49; }
    </style>
  </head>
  <body>
    <h1>Maintenance</h1>
    <p>The system is down for maintenance<br>
           as of <span class='date'><%= DateTime.now.strftime("%Y-%m-%d %H:%M") %></span> JST.</p>
    <p>It'll be back shortly.</p>
  </body>
</html>

app/frontend/app/views/layouts/sidebar/_services.html.haml
%a.nav-with-ul{href: 'javascript:void(0);'} 関連サービス
%span.nav-child-container
  %span.nav-child-trigger +

app/frontend/app/views/layouts/sidebar/_welcome.html.haml
%a.nav-with-ul{href: 'javascript:void(0);'} このサイトについて
%span.nav-child-container
  %span.nav-child-trigger +
%ul{style: "height: 0;"}
  %li
    = link_to 'お知らせ', blog_url
  %li
    = link_to '使い方', usage_path
  %li
    = link_to 'よくある質問', faq_path
  %li
    = link_to '利用規約', terms_path
  %li
    = link_to 'プライバシーポリシー', privacy_path
  %li
    = link_to 'お問い合わせ', contact_path

app/frontend/app/views/orders/new.html.haml
- content_for :scripts do
  :javascript
    $(document).ready(function() {
      $('#submit').click(function(e) {
        var collect_method = $('#job_parameter_collect_method').val();
        var archive_url    = $('#job_parameter_archive_url').val();
        if (collect_method == 'archive' && archive_url == '') {
          e.preventDefault();
          alert('全ツイート履歴のアップロードが必要です');
          return false;
        }
      });
    });

#content.blog.bg-dark
  #new
    = form_with url: order_path, method: :post, local: true do |f|
      = render 'orders/new/account'
      = render 'orders/new/method',  form: f
      = render 'orders/new/options', form: f
      = render 'orders/new/notices', form: f

      .primary-button.text-center(style='margin:8px')
        = f.submit '削除を開始する', class: 'button radius alert', id: 'submit'

app/frontend/app/views/orders/progressbar.html.haml
= render 'orders/show/progressbar', order: @order

app/frontend/app/views/orders/result.html.haml
#content.blog.bg-dark
  #result
    = render 'orders/result/score', order: @order
    = render 'orders/result/support', order: @order

  .primary-button.text-center(style='margin:8px')
    = button_to close_order_path, class: 'button radius' do
      DONE

app/frontend/app/views/orders/result/_score.html.haml
#score
  %article.post.format-aside
    .wrapped-content
      %h2.blog-title
        処理結果
      %dl
        %dt
          = t('.created_at')
        %dd
          = l(order.created_at, format: :long)
      %dl
        %dt
          = t('.state_completion')
        %dd
          = order.state_completion_message
      %dl
        %dt
          = t('.processing_time')
        %dd
          = order.processing_time
      %dl
        %dt
          = t('.collect_count')
        %dd
          = order.collect_count
          件
      %dl
        %dt
          = t('.destroy_count')
        %dd
          = order.destroy_count
          件

app/frontend/app/views/orders/result/_support.html.haml
#follow
  %article.post.format-aside
    .wrapped-content
      %p
        公式アカウントをフォローしよう<br>
        新機能のお知らせやサポートをしています<br>
      %p
        <a href="https://twitter.com/CleanThemAll" class="twitter-follow-button" data-show-count="false">Follow @CleanThemAll</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/frontend/app/views/orders/show.html.haml
- content_for :scripts do
  = render 'orders/scripts/progressbar'
  = render 'orders/scripts/status_dialog'

#content.blog.bg-dark
  #status
    %article.post.format-aside
      = flash_messages
      .wrapped-content
        #progressbar
          = render 'orders/show/progressbar', order: @order
        .text-center(style='margin-top:15px;')
          = link_to 'show more status', {}, 'data-remodal-target': 'modal'
      %hr.no-margin
      .wrapped-content.text-center
        = render partial: 'application/adsense/rectangle'
  .primary-button.text-center(style='margin:8px')
    #operation
      = button_to abort_order_path, class: 'button radius alert', form:{ style: 'display: inline-block;' } do
        キャンセル
      = button_to confirm_order_path, class: 'button radius', form: { style: 'display: inline-block;' } do
        結果を見る

#status-modal.remodal(data-remodal-id='modal')
  = render 'orders/show/status_dialog', order: @order, server_status: @server_status

app/frontend/app/views/orders/show/_progressbar.html.haml
.progress.bluegreen.radius
  #bar.meter(style='width:0%;')
.indicator#indicator.text-center
  = order.state_message

app/frontend/app/views/orders/show/_status_dialog.html.haml
%table
  %thead
    %tr
      %th.caption{:colspan => "2"} Server
  %tbody
    %tr
      %th 混雑度
      %td
        = server_status.busyness_i18n
    %tr
      %th 処理中
      %td
        = server_status.processing_count
        users
%table
  %thead
    %tr
      %th.caption{:colspan => "2"} Job
  %tbody
    %tr
      %th 処理対象
      %td
        = order.collect_count
        件
    %tr
      %th 削除済
      %td
        = order.destroy_count
        件
%table
  %thead
    %tr
      %th.caption{:colspan => "2"} Parameters
  %tbody
    %tr
      %th Name
      %td
        = order.user.name
    %tr
      %th From
      %td
        = order.parameter.collect_from
    %tr
      %th To
      %td
        = order.parameter.collect_to
    %tr
      %th
        Protect
        %br
        Reply
      %td
        = order.parameter.protect_reply_i18n
    %tr
      %th
        Protect
        %br
        Favorite
      %td
        = order.parameter.protect_favorite_i18n
    %tr
      %th Created At
      %td
        = l(order.parameter.created_at, format: :long)
%a.remodal-confirm{"data-remodal-action" => "confirm"} OK

app/frontend/app/views/orders/status_dialog.html.haml
= render 'orders/show/status_dialog', order: @order, server_status: @server_status

app/frontend/app/views/roots/contact.html.haml
#content.blog.scale-up.bg-dark
  #contact
    %article.post.format-aside
      .wrapped-content
        .wrapped-content
          %h3
            お問い合わせ
          %p
            下記ボタンからサポートアカウントまでお問い合わせ可能です。<br>
            ※ お問い合わせ・ご要望の前に、こちらの<a href='/cleaner/faq'>ヘルプ</a>に同様の質問・要望がないかご確認ください。
          %p
            = render :partial => 'roots/contact/mention'
          %hr
          %h3
            運営者情報
          %h4
            Twitter
          = render :partial => 'roots/contact/twitter'
          %h4
            Facebook
          = render :partial => 'roots/contact/facebook'

app/frontend/app/views/roots/contact/_facebook.html.haml
:plain
  <div id="fb-container" style="width:100%;">
    <div class="fb-like-box" data-href="https://www.facebook.com/cohakim" data-width="278" data-height="185" data-show-faces="true" data-stream="false" data-header="false"></div>
  </div>
  <div id="fb-root"></div>

  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=470879106306179";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    $(window).bind("load resize", function(){
      var container_width = $('#fb-container').width();
        $('#fb-container').html('<div class="fb-like-box" ' +
        'data-href="https://www.facebook.com/cohakim"' +
        ' data-width="' + container_width + '" data-height="262" data-show-faces="true" ' +
        'data-stream="false" data-header="false"></div>');
        FB.XFBML.parse( );
    });
  </script>

app/frontend/app/views/roots/contact/_mention.html.haml
:plain
  <div class='container'>
  <a href="https://twitter.com/intent/tweet?screen_name=CleanThemAll" class="twitter-mention-button" data-size="large" data-related="CleanThemAll">Tweet to @CleanThemAll</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  </div>

app/frontend/app/views/roots/contact/_twitter.html.haml
:plain
  <div class='container'>
  <a href="https://twitter.com/cohakim" class="twitter-follow-button" data-show-count="false">Follow @cohakim</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>

app/frontend/app/views/roots/faq.html.haml
#content.blog.scale-up.bg-dark
  #faq
    %article.post.format-aside
      .wrapped-content
        %h2.blog-title.text-center
          準備中です

app/frontend/app/views/roots/privacy.html.haml
#content.blog.scale-up.bg-dark
  #privacy
    %article.post.format-aside
      .wrapped-content
        %h2.blog-title.text-center
          準備中です

app/frontend/app/views/roots/show.html.haml
#content-fullwidth.blog.blog-single
  #getstarted
    %article.post.format-standard.text-center
      = flash_messages
      = render 'roots/show/primary'
      .wrapped-content(style='padding-top:7px;padding-bottom:0px;')
        = render partial: 'application/adsense/rectangle'
      = render 'roots/show/social'
      = render 'roots/show/features'
      = render 'roots/show/customers'
      .wrapped-content(style='padding-top:7px;padding-bottom:0px;')
        = render partial: 'application/adsense/rectangle'

app/frontend/app/views/roots/show/_customers.html.haml
.wrapped-content.bg-dark
  %p(style='margin-bottom:0px;')
    <strong>ツイート一括削除ツールの決定版( ^ω^ )</strong><br>
    あなたのお友達も使ってます！
  .primary-button
    - if logged_in?
      = link_to order_path, class: 'button radius' do
        ツイッターでログイン
    - else
      = link_to signin_path, method: :post, class: 'button radius' do
        ツイッターでログイン

app/frontend/app/views/roots/show/_features.html.haml
.wrapped-content
  %h3 Features
  %dl
    %dt
      %i.icon-back-in-time.feature
    %dd
      簡単登録、高速削除！<br>
      1分で始められ、10分で終わります
  %hr
  %dl
    %dt
      %i.icon-angellist.feature
    %dd
      バックグラウンド実行！<br>
      削除が始まればブラウザを起動しておく<br>
      必要はありません
  %hr
  %dl
    %dt
      %i.icon-tools.feature
    %dd
      多彩な削除オプション！<br>
      リプライやお気に入りの保護<br>
      特定日付のツイートだけ削除できます
  %hr
  %dl
    %dt
      %i.icon-cancel-circle.feature
    %dd
      削除をやめたくなった場合、<br>いつでもキャンセルすることができます

app/frontend/app/views/roots/show/_introduction.html.haml
.wrapped-content.bg-dark
  %p(style='margin-bottom:0px;')
    <strong>黒歴史クリーナー</strong>はツイートを<br>
    <mark class='yellow'>一括で削除</mark>できるサービスです！

app/frontend/app/views/roots/show/_primary.html.haml
.wrapped-content
  %h2.primary-title
    呪われしツイートを<br>一括削除！
  .primary-button
    - if logged_in?
      = link_to order_path, class: 'button radius' do
        ツイッターでログイン
    - else
      = link_to signin_path, method: :post, class: 'button radius' do
        ツイッターでログイン

app/frontend/app/views/roots/show/_social.html.haml
- content_for :scripts do
  <div id="fb-root"></div>
  :javascript
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=470879106306179";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

- content_for :scripts do
  :javascript
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

- content_for :scripts do
  :javascript
    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/platform.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();

.wrapped-content.bg-dark
  %p
    <strong>黒歴史クリーナー</strong>はツイートを<br>
    <mark class='yellow'>一括で削除</mark>できるサービスです！
  %ul.social-buttons
    %li.social-button
      <span><script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140127" ></script><script type="text/javascript">new media_line_me.LineButton({"pc":false,"lang":"ja","type":"e"});</script></span>
    %li.social-button
      <a href="https://twitter.com/share" class="twitter-share-button" data-count="vertical">Tweet</a>
    %li.social-button
      <div class="fb-like" data-href="https://kurorekishi.me/cleaner" data-layout="box_count" data-action="like" data-show-faces="false" data-share="false"></div>

app/frontend/app/views/roots/terms.html.haml
#content.blog.scale-up.bg-dark
  #terms
    %article.post.format-aside
      .wrapped-content
        %h2.blog-title.text-center
          準備中です

app/frontend/app/views/roots/usage.html.haml
#content.blog.scale-up.bg-dark
  #usage
    %article.post.format-aside
      .wrapped-content
        %h2.blog-title.text-center
          準備中です